<?php 
	$lenguaje = array(
		"Cerrar" => "Fermer",
		"Enviar" => "Envoyer",
		"Titulodealerta" => "Titre de l'alerte*",
		"Seleccionarusuario" => "Sélectionner un utilisateur*",
		"Usuario" => "Utilisateur",
		"Secretaria" => "Secrétaire",
		"JefedeBodega" => "Directeur d'entrepôt",
		"Empleados" => "Employés",
		"Clientes" => "Clients",
		"Todos" => "Tous",
		"Seleccionar" => "Sélectionner",
		"Correodelusuario" => "Mail utilisateur*",
		"Mensaje" => "Message*",
		"TitulodeCorreo" => "Titre du mail",
		"TitulodeNotifiacion" => "Titre de la notification*",
		"Notificaciones" => "Notifications",
		"MisNotificaciones" => "Mes notifications",
		"Alertas" => "Alertes",
		"Correos" => "Mail",
		"Visitas" => "Visites",
		"Cotizacion" => "Cotisation",
		"Cotizaciones" => "Citations",
		"Personal" => "Personnel",
		"Informes" => "Rapports",
		"Sistema" => "Système",
		"Configuracion" => "Configuration",
		"Administrador" => "Administrateur",

		"CambiarFotodePerfil"=>"Changer la photo de profil",
		"TerminosyCondiciones"=>"Termes et conditions",
		"Nombres"=>"Noms",
		"Apellidos"=>"Nom de famille",
		"Telefono"=>"Téléphone",
		"Correo"=>"Mail",
		"Contraseñaactual"=>"Mot de passe actuel",
		"NuevaContraseña"=>"Nouveau mot de passe",
		"ConfirmarContraseña"=>"Confirmer mot de passe",
		"ActualizarInformacion"=>"Mettre à jour les informations",


		"Evento"=>"Événement",
		"Eventos"=>"Événements",
		"Tipo"=>"Type",
		"Costo"=>"Coût",
		"Lugar"=>"Lieu",
		"Usuarios"=>"Les utilisateurs",
		"Estado"=>"Etat",
		"Buscar"=>"Chercher",
		"Nombre"=>"Nom",
		"Fecha"=>"Date",
		"Personas"=>"Les gens",
		"Tematica"=>"Thématique",
		"Anfitrion"=>"Hôte",
		"CostoTotal"=>"Coût total",
		"Banquete"=>"Banquet",
		"Formalidad"=>"La formalité",
		"Recordatorios"=>"Des rappels",
		"Comentarios"=>"Commentaires",
		"Verimplementos"=>"Voir les outils",
		"AsignarEmpleados"=>"Affecter des employés",
		"Devolver"=>"Retour",
		"Denegar"=>"Nier",
		"Aprobar"=>"Approuver",
		"Implementos"=>"Implements",
		"EmpleadosAsignados"=>"Employés assignés",
		"Cerrar"=>"Fermer",
		"Lugares"=>"Endroits",



		"Apellido"=>"Le nom",
		"Cargo"=>"Charge",
		"Honorarios"=>"Les frais",
		"Empleado"=>"Employé",
		"Cedula"=>"Carte d'identité",
		"Hojadevida"=>"Résumé",
		"FechadeContrato"=>"Date du contrat",
		"Despedir"=>"Le feu",
		"Modificar"=>"Modifier",
		"Aceptar"=>"Accepter",
		"Direccion"=>"Adresse",
		"Rol"=>"Rôle",

		"GananciasMensuales"=>"Gains mensuels",
		"Finanzas"=>"Les finances",
	);
 ?>