<?php 
	$lenguaje = array(
		"Cerrar" => "Fermer",
		"Notificaciones" => "Notifications",
		"Solicitud" => "Demande",
		"Solicitudes" => "Demandes",
		"Eventos" => "Événements",
		"Configuracion" => "Configuration",
		"Cliente" => "Client",
		"Cotizacion" => "Cotisation",
		"Aprobar"=>"Approuver",
		"Cancelar"=>"Annuler",

		"Aspirantes"=>"Aspirants",
		"CambiarFotodePerfil"=>"Changer la photo de profil",
		"TerminosyCondiciones"=>"Termes et conditions",
		"Nombres"=>"Noms",
		"Apellidos"=>"Nom de famille",
		"Telefono"=>"Téléphone",
		"Correo"=>"Mail",
		"Contraseñaactual"=>"Mot de passe actuel",
		"NuevaContraseña"=>"Nouveau mot de passe",
		"ConfirmarContraseña"=>"Confirmer mot de passe",


		"Solicitudes"=>"Demandes",
		"Tilulo"=>"Titre",
		"Evento"=>"Événement",
		"Tematica"=>"Thématique",
		"Lugar"=>"Lieu",
		"Estado"=>"Etat",
		"Buscar"=>"Chercher",
		"Fecha"=>"Date",
		"Usuario"=>"Nom d'utilisateur",
		"Anfitrion"=>"Hôte",
		"Personas"=>"Les gens",
		"Banquete"=>"Banquet",
		"Formalidad"=>"La formalité",
		"Recordatorios"=>"Des rappels",
		"Titulo"=>"Titre",
		"Costo"=>"Coût",
		"Comentarios"=>"Commentaires",

		"CostoMinimo"=>"Coût minier",
		"CostoMaximo"=>"Coût maximum",
		"Eliminar"=>"Enlever",
		"ActualizarInformacion"=>"Mettre à jour les informations",
	);
?>