<?php  
	$lenguaje = array(
		"Cerrar" => "Fermer",
		"Notificaciones" => "Notifications",
		"Solicitud" => "Demande",
		"Inventario" => "Inventaire",
		"Productos" => "produits",
		"Eventos" => "Événements",
		"Configuracion" => "Configuration",

		"Inventario"=>"Inventaire",
		"Evento"=>"Événement",
		"Tipo"=>"Type",
		"Costo"=>"Coût",
		"Lugar"=>"Lieu",	
		"Usuario"=>"Nom d'utilisateur",
		"Estado"=>"Etat",
		"Buscar"=>"Chercher",
		"Recordatorios"=>"Des rappels",
		"Personas"=>"Les gens",
		"Tematica"=>"Thématique",
		"CostoMinimo"=>"Coût minier",
		"CostoMaximo"=>"Coût maximum",
		"CostoTotal"=>"Coût total",
		"Aprobar"=>"Approuver",

		"Aspirantes"=>"Aspirants",
		"CambiarFotodePerfil"=>"Changer la photo de profil",
		"TerminosyCondiciones"=>"Termes et conditions",
		"Nombres"=>"Noms",
		"Apellidos"=>"Nom de famille",
		"Telefono"=>"Téléphone",
		"Correo"=>"Mail",
		"Contraseñaactual"=>"Mot de passe actuel",
		"NuevaContraseña"=>"Nouveau mot de passe",
		"ConfirmarContraseña"=>"Confirmer mot de passe",

		"Fecha"=>"Date",
		"Direccion"=>"Adresse",

		"Usuarios"=>"Les utilisateurs",

		"Implemento"=>"Implements",
		"Cotizacion"=>"Cotisation",
		"Cantidad"=>"Quantité",
		"Costototal"=>"Coût total",
		"EstasSeguroquequiereseliminaresteimplemento"=>"¿Êtes-vous sûr de vouloir supprimer cet outil?",
		"Eliminar"=>"Enlever",
		"Cancelar"=>"Annuler",
		"Modificar"=>"Modifier",
		"Costoporevento"=>"Coût par événement",
		"Nombre"=>"Nom",
		"Agregar"=>"Ajouter",
		"ActualizarInformacion"=>"Mettre à jour les informations",
	);
?>