<?php 
	$lenguaje =  array(
		"Cerrar" => "Fermer",
		"Notificaciones" => "Notifications",
		"Solicitud" => "Demande",
		"Solicitudes" => "Demandes",
		"Aspirantes" => "Aspirants",
		"Empleados" => "Émployés",
		"Configuracion" => "Configuration",
		"Secretaria" => "Secrétaire",

		"Aspirantes"=>"Aspirants",
		"Nombre"=>"Nom",
		"Correo"=>"Mail",
		"Telefono"=>"Téléphone",
		"Cedula"=>"Carte d'identité",
		"Cargo"=>"Charge",
		"Estado"=>"Etat",
		"Contratado"=>"Embauché",
		"Buscar"=>"Chercher",
		"Fecha"=>"Date",
		"Rol"=>"Rôle",
		"Apellido"=>"Le nom",
		"Foto"=>"Photo",
		"Hojadevida"=>"Résumé",
		"Eliminar"=>"Enlever",
		"Contratar"=>"Embaucher",

		"CambiarFotodePerfil"=>"Changer la photo de profil",
		"TerminosyCondiciones"=>"Termes et conditions",
		"Nombres"=>"Noms",
		"Apellidos"=>"Nom de famille",
		"Contraseñaactual"=>"Mot de passe actuel",
		"NuevaContraseña"=>"Nouveau mot de passe",
		"ConfirmarContraseña"=>"Confirmer mot de passe",
		"ActualizarInformacion"=>"Mettre à jour les informations",

		"Evento"=>"Événement",
		"Tematica"=>"Thématique",
		"Lugar"=>"Lieu",
		"Usuario"=>"Nom d'utilisateur",
		"Anfitrion"=>"Hôte",
		"Personas"=>"Les gens",
		"Banquete"=>"Banquet",
		"Formalidad"=>"La formalité",
		"Recordatorios"=>"Des rappels",
		"CostoMinimo"=>"Coût minier",
		"CostoMaximo"=>"Coût maximum",
		"Comentarios"=>"Commentaires",
		"Denegar"=>"Nie",
		"Aprobar"=>"Approuver",
		"Cerrar"=>"Fermer",
	);
 ?>