<?php 
	$lenguaje = array(
		"Cerrar" => "Cerrar",
		"Notificaciones" => "Notificaciones",
		"Solicitud" => "Solicitud",
		"Solicitudes" => "Solicitudes",
		"Eventos" => "Eventos",
		"Configuracion" => "Configuración",
		"Cliente" => "Cliente",
		"Cotizacion" => "Cotización",

		"Aspirantes"=>"Aspirantes",
		"CambiarFotodePerfil"=>"Cambiar Foto de Perfil",
		"TerminosyCondiciones"=>"Términos y Condiciones",
		"Nombres"=>"Nombres",
		"Apellidos"=>"Apellidos",
		"Telefono"=>"Teléfono",
		"Correo"=>"Correo",
		"Contraseñaactual"=>"Contraseña actual",
		"NuevaContraseña"=>"Nueva Contraseña",
		"ConfirmarContraseña"=>"Confirmar Contraseña",
		"Aprobar"=>"Aprobar",
		"Cancelar"=>"Cancelar",


		"Solicitudes"=>"Solicitudes",
		"Tilulo"=>"Título",
		"Evento"=>"Evento",
		"Tematica"=>"Temática",
		"Lugar"=>"Lugar",
		"Estado"=>"Estado",
		"Buscar"=>"Buscar",
		"Fecha"=>"Fecha",
		"Evento"=>"Evento",
		"Estado"=>"Estado",
		"Usuario"=>"Usuario",
		"Anfitrion"=>"Anfitrión",
		"Tematica"=>"Temática",
		"Lugar"=>"Lugar",
		"Personas"=>"Personas",
		"Banquete"=>"Banquete",
		"Formalidad"=>"Formalidad",
		"Recordatorios"=>"Recordatorios",
		"Titulo"=>"Título",
		"Costo"=>"Costo",
		"Comentarios"=>"Comentarios",

		"CostoMinimo"=>"Costo Mínimo",
		"CostoMaximo"=>"Costo Maximo",
		"Eliminar"=>"Eliminar",
		"ActualizarInformacion"=>"Actualizar Información",
	);
?>