<?php  
	$lenguaje = array(
		"Cerrar" => "Cerrar",
		"Notificaciones" => "Notificaciones",
		"Solicitud" => "Solicitud",
		"Inventario" => "Inventario",
		"Productos" => "Productos",
		"Eventos" => "Eventos",
		"Configuracion" => "Configuración",

		"Inventario"=>"Inventario",
		"Evento"=>"Evento",
		"Tipo"=>"Tipo",
		"Costo"=>"Costo",
		"Lugar"=>"Lugar",	
		"Usuario"=>"Usuario",
		"Estado"=>"Estado",
		"Buscar"=>"Buscar",
		"Tipo"=>"Tipo",
		"Lugar"=>"Lugar",
		"Recordatorios"=>"Recordatorios",
		"Personas"=>"Personas",
		"Tematica"=>"Temática",
		"CostoMinimo"=>"Costo Mínimo",
		"CostoMaximo"=>"Costo Maximo",
		"CostoTotal"=>"Costo Total",
		"Aprobar"=>"Aprobar",

		"Aspirantes"=>"Candidate",
		"CambiarFotodePerfil"=>"Cambiar Foto de Perfil",
		"TerminosyCondiciones"=>"Términos y Condiciones",
		"Nombres"=>"Nombres",
		"Apellidos"=>"Apellidos",
		"Telefono"=>"Teléfono",
		"Correo"=>"Correo",
		"Contraseñaactual"=>"Contraseña actual",
		"NuevaContraseña"=>"Nueva Contraseña",
		"ConfirmarContraseña"=>"Confirmar Contraseña",

		"Evento"=>"Evento",
		"Fecha"=>"Fecha",
		"Tematica"=>"Temática",
		"Lugar"=>"Lugar",
		"Direccion"=>"Dirección",
		"Buscar"=>"Buscar",

		"Tipo"=>"Tipo",
		"Costo"=>"Costo",
		"Lugar"=>"Lugar",
		"Usuarios"=>"Usuarios",
		"Estado"=>"Estado",
		"Buscar"=>"Buscar",

		"Inventario"=>"Inventario",
		"Implemento"=>"Implemento",
		"Tipo"=>"Tipo",
		"Cotizacion"=>"Cotización",
		"Evento"=>"Evento",
		"Cantidad"=>"Cantidad",
		"Costototal"=>"Costo total",
		"Estado"=>"Estado",
		"Buscar"=>"Buscar",
		"EstasSeguroquequiereseliminaresteimplemento"=>"¿Estás Seguro que quieres eliminar este implemento?",
		"Eliminar"=>"Eliminar",
		"Cancelar"=>"Cancelar",
		"Implemento"=>"Implemento",
		"Cantidad"=>"Cantidad",
		"Modificar"=>"Modificar",
		"Cancelar"=>"Cancelar",
		"Usuario"=>"Usuario",
		"CostoMinimo"=>"Costo Mínimo",
		"CostoMaximo"=>"Costo Maximo",
		"Aprobar"=>"Aprobar",
		"Recordatorios"=>"Recordatorios",
		"Personas"=>"Personas",
		"Costoporevento"=>"Costo por evento",
		"Nombre"=>"Nombre",
		"Agregar"=>"Agregar",
		"ActualizarInformacion"=>"Actualizar Información",
	);
?>