<?php 

	$lenguaje =  array(

		"Cerrar" => "Close",
		"Notificaciones" => "Notifications",
		"Mensajes" => "Messages",
		"UsuariosNuevos" => "New Users",
		"Visitas" => "Visits",
		"Solicitud" => "Request",
		"Solicitudes" => "Requests",
		"Aspirantes" => "Applicants",
		"Empleados" => "Employees",
		"Configuracion" => "Configuration",
		"Secretaria" => "Secretary",
		"menulenguaje" => "English",

		"Aspirantes"=>"Applicants",
		"Nombre"=>"Name",
		"Correo"=>"Mail",
		"Telefono"=>"Telephone",
		"Cedula"=>"Identification card",
		"Cargo"=>"Position",
		"Estado"=>"Status",
		"Contratado"=>"Hired",
		"Buscar"=>"Search",
		"Fecha"=>"Date",
		"Rol"=>"Rol",
		"Nombre"=>"Name",
		"Apellido"=>"Surname",
		"Correo"=>"Mail",
		"Telefono"=>"Telephone",
		"Estado"=>"Status",
		"Foto"=>"Photo",
		"Hojadevida"=>"Life Lea",
		"Eliminar"=>"Delete",
		"Contratar"=>"Hire",

		"CambiarFotodePerfil"=>"Change Profile Picture",
		"TerminosyCondiciones"=>"Terms and Conditions",
		"Nombres"=>"Name",
		"Apellidos"=>"Surnames",
		"Telefono"=>"Phone",
		"Correo"=>"Mail",
		"Contraseñaactual"=>"Current password",
		"NuevaContraseña"=>"New Password",
		"ConfirmarContraseña"=>"Confirm Password",
		"ActualizarInformacion"=>"Update information",


		"Empleados"=>"Employees",
		"Nombre"=>"NName",
		"Apellido"=>"Surname",
		"Rol"=>"Rol",
		"Correo"=>"Mail",
		"Estado"=>"Status",
		"Buscar"=>"Search",
		"Fecha"=>"Date",
		"Rol"=>"Rol",
		"Nombre"=>"Name",
		"Apellido"=>"Surname",
		"Correo"=>"Mail",
		"Telefono"=>"Telephone",
		"Cedula"=>"Identification card",
		"Estado"=>"Status",
		"Foto"=>"Photo",
		"Hojadevida"=>"Life Sheet",

		"Solicitudes"=>"Requests",
		"Evento"=>"Event",
		"Tematica"=>"Thematic",
		"Lugar"=>"Plaves",
		"Usuario"=>"User",
		"Estado"=>"Status",
		"Buscar"=>"Search",
		"Fecha"=>"Date",
		"Evento"=>"Event",
		"Estado"=>"Status",
		"Usuario"=>"Users",
		"Anfitrion"=>"Host",
		"Tematica"=>"Thematic",
		"Lugar"=>"Places",
		"Personas"=>"People",
		"Banquete"=>"Banquet",
		"Formalidad"=>"Formality",
		"Recordatorios"=>"Reminders",
		"CostoMinimo"=>"Minimum Cost",
		"CostoMaximo"=>"Maximum Cost",
		"Comentarios"=>"Comements",
		"Denegar"=>"Deny",
		"Aprobar"=>"Approve",
		"Cerrar"=>"Close",
	);


 ?>